menu:
  Blog: /blog/
  About: /
  Contact: mailto:david@davidhogue.com
  Subscribe: /blog/atom.xml

widgets: 
#- search
#- category
#- tag
#- twitter
- recent_posts
- ads

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss: